#!/bin/sh

case "$1" in
    start)
        echo "Starting aesd modules"
        aesdchar_load
        ;;
    stop)
        echo "Stopping aesd modules"
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0